server: #端口号
  port: ${huangou-upload-service.port}


spring:
  application: #名称
    name: huangou-upload-service
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${huangou-registry.port}/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true  #定义死ip地址
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 192.168.56.101:22122

